build:
  image: ubuntu:14.04
  commands:
    - apt-get install -y build-essential libpcre3-dev libssl-dev zlib1g-dev
    - hg clone -b release-1.9.13 http://hg.nginx.org/nginx
    - ./build

clone:
  depth: 1
