#!/bin/sh -eux

if [ -z "$1" ]; then
    echo "Usage: build REVISION" >&2
    exit 1
fi
revision="$1"

umask 022

base_dir="$(readlink -f -- "$(dirname "$0")/..")"
output_dir="${base_dir}/deb"
repo_dir="${base_dir}/repo"
assets_dir="${base_dir}/assets"
package_dir="${base_dir}/pkg"
rm -rf "${package_dir}"
mkdir "${package_dir}"

cd "${repo_dir}"

: "=========== configure ==========="
./auto/configure \
    --prefix=/srv/nginx \
    --sbin-path=/usr/local/sbin/nginx \
    --conf-path=/etc/nginx/nginx.conf \
    --error-log-path=/var/log/nginx/error.log \
    --pid-path=/run/nginx.pid \
    --lock-path=/run/lock \
    --user=nginx \
    --group=nginx \
    --build=nojima \
    --with-threads \
    --with-ipv6 \
    --with-http_ssl_module \
    --with-http_v2_module \
    --with-http_gzip_static_module \
    --with-http_stub_status_module \
    --http-log-path=/var/log/nginx/access.log \
    --http-client-body-temp-path=/var/lib/nginx/client-body \
    --http-proxy-temp-path=/var/lib/nginx/proxy \
    --http-fastcgi-temp-path=/var/lib/nginx/fastcgi \
    --http-uwsgi-temp-path=/var/lib/nginx/uwsgi \
    --http-scgi-temp-path=/var/lib/nginx/scgi \
    --with-pcre \
    --with-pcre-jit \
    --with-debug

: "=========== make ==========="
make -j "$(nproc)"
DESTDIR="${package_dir}" make install

# Remove default config files.
rm -r "${package_dir}/etc/nginx"
mkdir "${package_dir}/etc/nginx"
rm -r "${package_dir}/srv/nginx"
mkdir "${package_dir}/srv/nginx"

# Copy base config.
mkdir -p "${package_dir}/etc/nginx/conf.d"
mkdir -p "${package_dir}/etc/nginx/sites"
cp "${assets_dir}/nginx.conf" "${package_dir}/etc/nginx"
cp "${assets_dir}/sites-system.conf" "${package_dir}/etc/nginx/sites/system.conf"

# Copy systemd unit.
mkdir -p "${package_dir}/lib/systemd/system"
cp "${assets_dir}/nginx.service" "${package_dir}/lib/systemd/system"

# Copy utilities.
mkdir -p "${package_dir}/usr/local/share/nginx/bin"
cp "${assets_dir}/nginx-prestart" "${package_dir}/usr/local/share/nginx/bin"
cp "${assets_dir}/nginx-reload" "${package_dir}/usr/local/share/nginx/bin"
cp "${assets_dir}/nginx-status" "${package_dir}/usr/local/share/nginx/bin"

# Calculate installed size.
installed_size="$(du --apparent-size --summarize -- "${package_dir}" | cut -f1)"

# Create control files.
mkdir "${package_dir}/DEBIAN"

nginx_version=$("${package_dir}/usr/local/sbin/nginx" -v 2>&1 | perl -ne '/nginx\/([0-9.]+)/ && print $1')
cat > "${package_dir}/DEBIAN/control" <<EOF
Package: nojima-nginx
Priority: optional
Section: web
Installed-Size: ${installed_size}
Version: ${nginx_version}-${revision}
Maintainer: Yusuke Nojima <nojima@ynojima.com>
Architecture: amd64
Depends: libpcre3, libssl1.0.0, zlib1g, curl
Description: An HTTP and reverse proxy server
EOF

# Create conffiles.
(cd "$package_dir" && find ./etc -type f | cut --bytes 2-) > "${package_dir}/DEBIAN/conffiles"

# Copy maintainer scripts.
cp "${assets_dir}/postinst" "${package_dir}/DEBIAN/postinst"
cp "${assets_dir}/prerm" "${package_dir}/DEBIAN/prerm"

: "=========== dpkg-deb --build ==========="
mkdir -p "${output_dir}"
fakeroot dpkg-deb --build "${package_dir}" "${output_dir}"
